# Configuration for evaluation pipeline
use_llm_generated: true
llm_generated_dataset: "rtweera/fmt-q-and-a-together-part-14-76qty"
llm_mapper:
  question: "question"
  answer: "answer"

use_copilot: false
copilot_dataset: "<your-username>/<copilot-dataset>"
copilot_mapper:
  question: "question"
  answer: "assistant_message"

use_base: true
base_dataset: "rtweera/2025-Jun-08_16-24-12_outputof_Qwen2.5-7B-Instruct-unsloth-bnb-4bit"
base_mapper:
  question: "user_prompt"
  answer: "assistant"

use_fine_tuned: true
fine_tuned_dataset: "rtweera/2025-Jun-06_15-38-56_outputof_2025-Jun-06_15-05-53_Qwen2.5-7B-Instruct-unsloth-bnb-4bit_LoRA"
fine_tuned_mapper:
  question: "user_prompt"
  answer: "assistant"

# Column names in the datasets
system_prompt_column: "system_prompt"

# Ragas evaluation settings
ragas:
  metric: "answer_similarity"
  embedding_model: "text-embedding-3-small"

# Output
output_metrics_file: "ragas_metrics.csv"
output_merged_file: "merged_eval_data.csv"
